src/EC_Website.Web/Pages/Admin/UserBadges/Create.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Core.Interfaces.Repositories;
using EC_Website.Web.Authorization;

namespace EC_Website.Web.Pages.Admin.UserBadges
{
    [Authorize(Policy = Policies.HasAdminRole)]
    public class CreateModel : PageModel
    {
        private readonly IRepository _repository;

        public CreateModel(IRepository repository)
        {
            _repository = repository;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Badge Badge { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await _repository.AddAsync(Badge);
            return RedirectToPage("./Index");
        }
    }
}

src/EC_Website.Web/Pages/Admin/UserBadges/Delete.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Core.Interfaces.Repositories;
using EC_Website.Web.Authorization;

namespace EC_Website.Web.Pages.Admin.UserBadges
{
    [Authorize(Policy = Policies.HasAdminRole)]
    public class DeleteModel : PageModel
    {
        private readonly IRepository _repository;

        public DeleteModel(IRepository repository)
        {
            _repository = repository;
        }

        [BindProperty]
        public Badge Badge { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Badge = await _repository.GetByIdAsync<Badge>(id);

            if (Badge == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await _repository.DeleteAsync(Badge);
            return RedirectToPage("./Index");
        }
    }
}

src/EC_Website.Web/Pages/Admin/UserBadges/Edit.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Core.Interfaces.Repositories;
using EC_Website.Web.Authorization;

namespace EC_Website.Web.Pages.Admin.UserBadges
{
    [Authorize(Policy = Policies.HasAdminRole)]
    public class EditModel : PageModel
    {
        private readonly IRepository _repository;

        public EditModel(IRepository repository)
        {
            _repository = repository;
        }

        [BindProperty]
        public Badge Badge { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Badge = await _repository.GetByIdAsync<Badge>(id);

            if (Badge == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var badge = await _repository.GetByIdAsync<Badge>(Badge.Id);

            if (badge == null)
            {
                return NotFound();
            }

            badge.Name = Badge.Name;
            badge.Description = Badge.Description;
            await _repository.UpdateAsync(badge);
            return RedirectToPage("./Index");
        }
    }
}

src/EC_Website.Web/Pages/Admin/UserRoles/Edit.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Web.Authorization;

namespace EC_Website.Web.Pages.Admin.UserRoles
{
    [Authorize(Policy = Policies.HasAdminRole)]
    public class EditModel : PageModel
    {
        private readonly RoleManager<UserRole> _roleManager;

        public EditModel(RoleManager<UserRole> roleManager)
        {
            _roleManager = roleManager;
        }

        [BindProperty]
        public UserRole UserRole { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            UserRole = await _roleManager.FindByIdAsync(id);

            if (UserRole == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var userRole = await _roleManager.FindByIdAsync(UserRole.Id);

            if (userRole == null)
            {
                return NotFound();
            }
            
            userRole.Description = UserRole.Description;
            await _roleManager.UpdateAsync(userRole);
            return RedirectToPage("./Index");
        }
    }
}

src/EC_Website.Web/Pages/Admin/Users/Create.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Web.Authorization;

namespace EC_Website.Web.Pages.Admin.Users
{
    [Authorize(Policy = Policies.HasAdminRole)]
    public class CreateModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<CreateModel> _logger;

        public CreateModel(UserManager<ApplicationUser> userManager,
            ILogger<CreateModel> logger)
        {
            _userManager = userManager;
            _logger = logger;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public string ReturnUrl { get; set; }

        public class InputModel
        {
            [Required]
            [DataType(DataType.Text)]
            [Display(Name = "Username")]
            public string Username { get; set; }

            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm Password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }
        }

        public void OnGet(string returnUrl = null)
        {
            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/");

            if (!ModelState.IsValid) 
                return Page();

            var user = new ApplicationUser
            {
                UserName = Input.Username,
                Email = Input.Email,
                EmailConfirmed = true
            };

            var result = await _userManager.CreateAsync(user, Input.Password);
            if (!result.Succeeded) 
                return Page();

            _logger.LogInformation("User created a new account with password in admin page");
            return LocalRedirect(returnUrl);

        }
    }
}

src/EC_Website.Web/Pages/Admin/Users/Delete.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Core.Interfaces.Repositories;

namespace EC_Website.Web.Pages.Admin.Users
{
    [Authorize(Roles = "SuperAdmin")]
    public class DeleteModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUserRepository _userRepository;

        public DeleteModel(IUserRepository userRepository, UserManager<ApplicationUser> userManager)
        {
            _userRepository = userRepository;
            _userManager = userManager;
        }

        [BindProperty]
        public ApplicationUser AppUser { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            AppUser = await _userManager.Users.FirstOrDefaultAsync(i => i.Id == id);

            if (User == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            await _userRepository.DeleteDeeplyAsync(user);
            return RedirectToPage("./Index");
        }
    }
}

src/EC_Website.Web/Pages/Admin/Users/Edit.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Core.Interfaces.Repositories;
using EC_Website.Infrastructure.Extensions;
using EC_Website.Web.Authorization;
using EC_Website.Web.Utils;

namespace EC_Website.Web.Pages.Admin.Users
{
    [Authorize(Policy = Policies.HasAdminRole)]
    public class EditModel : PageModel
    {
        private readonly IUserRepository _userRepository;
        private readonly RoleManager<UserRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ImageHelper _imageHelper;

        public EditModel(UserManager<ApplicationUser> userManager,
            RoleManager<UserRole> roleManager, ImageHelper imageHelper,
            IUserRepository userRepository)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _userRepository = userRepository;
            _imageHelper = imageHelper;
        }

        [BindProperty]
        public ApplicationUser AppUser { get; set; }

        [BindProperty]
        public IList<string> UserRolesName { get; set; }

        [BindProperty]
        public IList<string> UserBadgesName { get; set; }

        [BindProperty]
        public IFormFile ProfilePhoto { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            AppUser = await _userManager.FindByIdAsync(id);

            if (AppUser == null)
            {
                return NotFound();
            }

            var isUserRoleLower = await _userManager.CheckRoleLowerOrEqualAsync(User, AppUser);
            if (isUserRoleLower)
            {
                return LocalRedirect("/Identity/Account/AccessDenied");
            }

            List<UserRole> userRoles;
            if (User.IsInRole("SuperAdmin"))
            {
                // Only SuperAdmin can assign Admin or SuperAdmin roles
                userRoles = await _roleManager.Roles.ToListAsync();
            }
            else
            {
                // Exclude SuperAdmin and Admin roles
                userRoles = await _roleManager.Roles.Where(i => i.Role != Role.SuperAdmin && i.Role != Role.Admin).ToListAsync();
            }
            
            var userBadges = await _userRepository.GetListAsync<Badge>();
            ViewData.Add("userRoles", userRoles);
            ViewData.Add("userBadges", userBadges.Select(i => i.Name));

            UserRolesName = await _userManager.GetRolesAsync(AppUser);
            UserBadgesName = AppUser.UserBadges.Select(i => i.Badge.Name).ToList();

            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var user = await _userManager.FindByIdAsync(AppUser.Id);

            if (user == null)
            {
                return NotFound();
            }

            user.UserName = AppUser.UserName;
            user.Email = AppUser.Email;
            user.FirstName = AppUser.FirstName;
            user.LastName = AppUser.LastName;
            user.PhoneNumber = AppUser.PhoneNumber;
            user.Status = AppUser.Status;
            user.Bio = AppUser.Bio;
            user.IsBanned = AppUser.IsBanned;
            user.BanExpirationDate = AppUser.BanExpirationDate;
            await _userRepository.UpdateUserBadgesAsync(user, UserBadgesName);
            await _userRepository.UpdateUserRolesAsync(user, UserRolesName);

            if (ProfilePhoto != null)
            {
                user.ProfilePhotoPath = _imageHelper.UploadImage(ProfilePhoto, $"{user.Id}_profile", true);
            }

            await _userManager.UpdateAsync(user);
            return RedirectToPage("./Index");
        }
    }
}

src/EC_Website.Web/Pages/Forums/Search/Index.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EC_Website.Web.ViewModels;

namespace EC_Website.Web.Pages.Forums.Search
{
    public class IndexModel : PageModel
    {
        public IActionResult OnGet([FromQuery] SearchViewModel filter)
        {
            return filter.PageType switch
            {
                SearchPageType.Posts => RedirectToPage("./Post", filter),
                SearchPageType.Threads => RedirectToPage("./Thread", filter),
                _ => Page()
            };
        }
    }
}

src/EC_Website.Web/ViewComponents/AlertBoxViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Web.ViewModels;

namespace EC_Website.Web.ViewComponents
{
    public class AlertBoxViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(string message, AlertType alertType = AlertType.Success, bool dismissible = true)
        {
            var alertBox = new AlertBoxViewModel(message)
            {
                AlertType = alertType,
                IsDismissible = dismissible
            };
            return View(alertBox);
        }
    }
}

src/EC_Website.Web/ViewComponents/SearchBoxViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using EC_Website.Web.ViewModels;

namespace EC_Website.Web.ViewComponents
{
    public class SearchBoxViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var viewModel = new SearchViewModel();
            return View(viewModel);
        }
    }
}

src/EC_Website.Web/ViewComponents/UserBadgesViewComponent.cs
using System.Collections.Generic;
using Microsoft.AspNetCore.Mvc;
using EC_Website.Core.Entities.UserModel;

namespace EC_Website.Web.ViewComponents
{
    public class UserBadgesViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(ApplicationUser user)
        {
            return View(user);
        }
    }
}

src/EC_Website.Web/ViewComponents/UserRolesViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using EC_Website.Core.Entities.UserModel;

namespace EC_Website.Web.ViewComponents
{
    public class UserRolesViewComponent : ViewComponent
    {
        private readonly UserManager<ApplicationUser> _userManager;

        public UserRolesViewComponent(UserManager<ApplicationUser> userManager)
        {
            _userManager = userManager;
        }

        public async Task<IViewComponentResult> InvokeAsync(ApplicationUser user)
        {
            var roles = await _userManager.GetRolesAsync(user);
            return View(roles);
        }
    }
}

src/EC_Website.Web/Pages/Forums/Thread/Create.cshtml
@page
@model EC_Website.Web.Pages.Forums.Thread.CreateModel
@inject IAuthorizationService Authorization
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["Create Thread"];
}

@section Head {
    <partial name="_SyncfusionScriptsPartial" />
}

<h1>@ViewData["Title"]</h1>

<h4>@Localizer["Start new thread in"]: <span class="text-info">@Model.Thread.Board.Title</span> </h4>
<hr />
<div class="row">
    <div class="col-12 col-md-8">
        <form method="post" asp-route-boardId="@Model.Thread.Board.Id">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Thread.Title" class="control-label"></label><span class="font-weight-bold text-danger">*</span>
                <input asp-for="Thread.Title" class="form-control" />
            </div>
            
            @if ((await Authorization.AuthorizeAsync(User, Policies.CanManageForums)).Succeeded)
            {
                <div class="form-group">
                    <label asp-for="Thread.IsLocked" class="form-check-label"></label>
                    <input asp-for="Thread.IsLocked" class="form-check-inline" />
                </div>
                <div class="form-group">
                    <label asp-for="Thread.IsPinned" class="form-check-label"></label>
                    <input asp-for="Thread.IsPinned" class="form-check-inline" />
                </div>
            }
            
            <div class="form-group">
                <label class="control-label" asp-for="Post.Content"></label><span class="font-weight-bold text-danger">*</span>
                <span asp-validation-for="Post.Content" class="text-danger"></span>
                <ejs-richtexteditor id="rich_texteditor" ejs-for="Post.Content" height="300">
                    <e-richtexteditor-toolbarsettings items="@ViewData["toolbar"]" enableFloating="true">
                    </e-richtexteditor-toolbarsettings>
                </ejs-richtexteditor>
            </div>
            <div class="form-group">
                <input type="submit" value="@Localizer["Create"]" class="btn btn-success" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="../Board/Index" asp-route-slug="@Model.Thread.Board.Slug">@Localizer["Back to List"]</a>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/EC_Website.Web/Pages/Forums/Thread/Index.cshtml
@page "{slug}"
@model EC_Website.Web.Pages.Forums.Thread.IndexModel
@inject IViewLocalizer Localizer
@inject IAuthorizationService Authorization
@inject RealTimeDataContext RealTimeContext
@inject UserManager<ApplicationUser> UserManager

@{
    ViewData["Title"] = Model.Thread.Title;
}

@section Head {
    @{
        var threadUrl = $"https://ec-hoi-mod.site/{Model.Thread.Slug}";
    }

    <meta name="author" content="@Model.Thread.Author.UserName" />
    <meta name="description" content="Thread @Model.Thread.Title - Economic Crisis Forum" />
    <meta name="keywords" content="global strategy, rts, game, hoi4, ec, economic crisis, economic crisis 2013, hoi 4, hoi4, hoi 4, hoi IV, hoi ec, hoi4 ec, mod, hearts of iron 4, hearts of iron IV, economic crisis forum" />
    <meta property="og:title" content="@Model.Thread.Title" />
    <meta property="og:description" content="Thread @Model.Thread.Title - Economic Crisis Forum" />
    <meta property="og:site_name" content="Thread @Model.Thread.Title - Economic Crisis Forum" />
    <meta property="og:url" content="@threadUrl" />
    <meta name="twitter:title" content="@Model.Thread.Title" />
    <meta name="twitter:description" content="Thread @Model.Thread.Title - Economic Crisis Forum" />
    <meta name="twitter:creator" content="@Model.Thread.Author.UserName" />
    <meta name="twitter:card" content="@Model.Thread.Title" />
    <meta name="twitter:site" content="Thread @Model.Thread.Title - Economic Crisis Forum" />

    <partial name="_SyncfusionScriptsPartial" />
    <link href="~/css/forum-theme.css" rel="stylesheet" />
}

<div class="forum">
    <div class="forum-header">
        <div class="row">
            <div class="col-9 col-md-10">
                <h1>@Model.Thread.Title</h1>
            </div>
            <div class="col-3 col-md-2">
                @if ((await Authorization.AuthorizeAsync(User, Policies.CanManageForums)).Succeeded)
                {
                    <span class="float-right mt-2">
                        <a asp-page="./Edit" asp-route-id="@Model.Thread.Id" class="text-light" data-toggle="tooltip" data-placement="top" title="@Localizer["Edit thread"]"><i class="fas fa-wrench fa-lg"></i></a>
                        <a asp-page="./Delete" asp-route-id="@Model.Thread.Id" class="text-light" data-toggle="tooltip" data-placement="top" title="@Localizer["Delete thread"]"><i class="fas fa-times fa-lg"></i></a>
                    </span>
                }
            </div>
        </div>

        <ul class="breadcrumb text-primary mt-1 mb-0">
            <li class="breadcrumb-item"><a asp-page="../Index">@Model.Thread.Board.Forum.Title</a></li>
            <li class="breadcrumb-item"><a asp-page="../Board/Index" asp-route-slug="@Model.Thread.Board.Slug">@Model.Thread.Board.Title</a></li>
            <li class="breadcrumb-item"><a asp-page="../Thread/Index" asp-route-slug="@Model.Thread.Slug">@Model.Thread.Title</a></li>
        </ul>
    </div>

    <div class="forum-body">
        <div class="forum-search-panel">
            <vc:search-box />
        </div>
        <div class="table-responsive">
            <table id="tableforum" class="table table-bordered">
                <thead class="forum-table-head">
                    <tr>
                        <th width="110">
                            <strong>@Localizer["Author"]</strong>
                        </th>
                        <th>
                            <strong>@Localizer["Posts"]</strong>
                        </th>
                    </tr>
                    <tr class="forum-category">
                        <th>
                        </th>
                        <th style="background-color: teal; text-align: center">
                            @if (Model.Thread.IsLocked)
                            {
                                <strong>@Localizer["Locked"]</strong>
                            }
                            else
                            {
                                <a style="color: azure" href="#post_reply"><strong>@Localizer["Post Reply"]</strong></a>
                            }
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @{
                        var posts = Model.Posts.OrderBy(i => i.Timestamp).ToList();
                    }
                    @foreach (var post in posts)
                    {
                        <tr>
                            <td></td>
                            <td style="background-color: antiquewhite">
                                <a role="button" class="btn btn-sm" href="#post_reply" onclick="quoteToPost('@post.Id', '@post.Author.UserName')"><b>@Localizer["Quote"]</b></a>
                                <span class="float-right">
                                    <span class="mr-1">@post.Timestamp.ToString("MMM dd yyyy HH:mm")</span>

                                    @if ((await Authorization.AuthorizeAsync(User, Policies.CanBanUsers)).Succeeded)
                                    {
                                        <a asp-page="/Admin/Users/Restrict" asp-route-id="@post.Author.Id" asp-route-returnUrl="/Forums/Thread/Index/@Model.Thread.Slug"
                                           class="text-dark" data-toggle="tooltip" data-placement="top" title="@Localizer["Edit user ban"]">
                                            <i class="fas fa-ban"></i>
                                        </a>
                                    }

                                    @if (User.Identity.Name == post.Author.UserName ||
                                     (await Authorization.AuthorizeAsync(User, Policies.CanManageForums)).Succeeded)
                                    {

                                        <a asp-page="./EditPost" asp-route-postId="@post.Id" class="text-dark" data-toggle="tooltip" data-placement="top" title="@Localizer["Edit post"]"><i class="fas fa-wrench"></i></a>

                                        if (post.Id != posts.First().Id)
                                        {
                                            <a asp-page="./DeletePost" asp-route-postId="@post.Id" class="text-dark" data-toggle="tooltip" data-placement="top" title="@Localizer["Delete post"]"><i class="fas fa-minus-circle"></i></a>
                                        }
                                    }
                                </span>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                @{
                                    <div class="img-container" style="cursor: pointer">
                                        @{
                                            var userOnline = RealTimeContext.OnlineUsers.Contains(post.Author.UserName);
                                            var statusColor = userOnline ? "bg-success" : "bg-secondary";
                                        }
                                        <div class="status-icon-forum @statusColor"></div>
                                        <img class="rounded" src="@post.Author.ProfilePhotoPath" alt="@post.Author.UserName photo" style="height: 70px; width: 70px" onclick="window.location = '/User/@post.Author.UserName'" />
                                    </div>
                                    <a asp-page="/User/Index" asp-route-username="@post.Author.UserName">@post.Author.UserName</a><br />
                                    <vc:user-roles user="@post.Author" />
                                    <vc:user-badges user="@post.Author" />
                                }
                            </td>
                            <td id="@post.Id" class="forum-post">
                                @Html.Raw(post.Content)
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="2">
                            <div id="pagination" class="d-flex">
                                <pagination class="mx-auto" page-index="@Model.Posts.PageIndex" total-pages="@Model.Posts.TotalPages"
                                            page-path="/Forums/Thread/@Model.Thread.Slug" />
                            </div>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>

<div id="post_reply" class="container-fluid mt-3" style="background-color: black; border-radius: 10px;">
    @if (User.Identity.IsAuthenticated && !Model.Thread.IsLocked)
    {
        var user = await UserManager.GetUserAsync(User);
        if (user.IsBanned)
        {
            <vc:alert-box alert-type="@AlertType.Error" dismissible="true"
                          message="You banned, and you can not write posts until @user.BanExpirationDate?.ToShortDateString()" />
        }
        else
        {
            <form method="post" asp-page-handler="AddPost">
                <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                <label class="font-weight-bold" style="color: aliceblue">@Localizer["Reply to thread"]</label>
                <span asp-validation-for="PostContent" class="text-danger"></span>
                <ejs-richtexteditor id="rich_texteditor" ejs-for="PostContent" height="300">
                    <e-richtexteditor-toolbarsettings items="@ViewData["toolbar"]" enableFloating="true">
                    </e-richtexteditor-toolbarsettings>
                </ejs-richtexteditor>
                <input type="submit" class="btn btn-light my-2" value="@Localizer["Post Reply"]" />
            </form>
        }
    }
</div>

@section Scripts {
    <script>
        function quoteToPost(postId = "", postAuthorName = "") {
            const postNode = document.createElement("blockquote");
            postNode.className = "blockquote p-1";
            postNode.style = "border-left: 5px solid #f86466";
            postNode.innerHTML = document.getElementById(`${postId}`).innerHTML;

            const blockquoteFooter = document.createElement("footer");
            blockquoteFooter.className = "blockquote-footer";
            blockquoteFooter.innerText = postAuthorName;
            blockquoteFooter.style = "font-size: 50%";
            postNode.append(blockquoteFooter);

            document.getElementById("rich_texteditor_rte-edit-view").append(postNode);
        }
    </script>
}