src/EC_Website.Web/Pages/Admin/UserBadges/Create.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Core.Interfaces.Repositories;
using EC_Website.Web.Authorization;

namespace EC_Website.Web.Pages.Admin.UserBadges
{
    [Authorize(Policy = Policies.HasAdminRole)]
    public class CreateModel : PageModel
    {
        private readonly IRepository _repository;

        public CreateModel(IRepository repository)
        {
            _repository = repository;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Badge Badge { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await _repository.AddAsync(Badge);
            return RedirectToPage("./Index");
        }
    }
}

src/EC_Website.Web/Pages/Admin/UserBadges/Delete.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Core.Interfaces.Repositories;
using EC_Website.Web.Authorization;

namespace EC_Website.Web.Pages.Admin.UserBadges
{
    [Authorize(Policy = Policies.HasAdminRole)]
    public class DeleteModel : PageModel
    {
        private readonly IRepository _repository;

        public DeleteModel(IRepository repository)
        {
            _repository = repository;
        }

        [BindProperty]
        public Badge Badge { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Badge = await _repository.GetByIdAsync<Badge>(id);

            if (Badge == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await _repository.DeleteAsync(Badge);
            return RedirectToPage("./Index");
        }
    }
}

src/EC_Website.Web/Pages/Admin/UserBadges/Edit.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Core.Interfaces.Repositories;
using EC_Website.Web.Authorization;

namespace EC_Website.Web.Pages.Admin.UserBadges
{
    [Authorize(Policy = Policies.HasAdminRole)]
    public class EditModel : PageModel
    {
        private readonly IRepository _repository;

        public EditModel(IRepository repository)
        {
            _repository = repository;
        }

        [BindProperty]
        public Badge Badge { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Badge = await _repository.GetByIdAsync<Badge>(id);

            if (Badge == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var badge = await _repository.GetByIdAsync<Badge>(Badge.Id);

            if (badge == null)
            {
                return NotFound();
            }

            badge.Name = Badge.Name;
            badge.Description = Badge.Description;
            await _repository.UpdateAsync(badge);
            return RedirectToPage("./Index");
        }
    }
}

src/EC_Website.Web/Pages/Admin/UserRoles/Edit.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Web.Authorization;

namespace EC_Website.Web.Pages.Admin.UserRoles
{
    [Authorize(Policy = Policies.HasAdminRole)]
    public class EditModel : PageModel
    {
        private readonly RoleManager<UserRole> _roleManager;

        public EditModel(RoleManager<UserRole> roleManager)
        {
            _roleManager = roleManager;
        }

        [BindProperty]
        public UserRole UserRole { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            UserRole = await _roleManager.FindByIdAsync(id);

            if (UserRole == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var userRole = await _roleManager.FindByIdAsync(UserRole.Id);

            if (userRole == null)
            {
                return NotFound();
            }
            
            userRole.Description = UserRole.Description;
            await _roleManager.UpdateAsync(userRole);
            return RedirectToPage("./Index");
        }
    }
}

src/EC_Website.Web/Pages/Admin/Users/Create.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Web.Authorization;

namespace EC_Website.Web.Pages.Admin.Users
{
    [Authorize(Policy = Policies.HasAdminRole)]
    public class CreateModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<CreateModel> _logger;

        public CreateModel(UserManager<ApplicationUser> userManager,
            ILogger<CreateModel> logger)
        {
            _userManager = userManager;
            _logger = logger;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public string ReturnUrl { get; set; }

        public class InputModel
        {
            [Required]
            [DataType(DataType.Text)]
            [Display(Name = "Username")]
            public string Username { get; set; }

            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm Password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }
        }

        public void OnGet(string returnUrl = null)
        {
            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/");

            if (!ModelState.IsValid) 
                return Page();

            var user = new ApplicationUser
            {
                UserName = Input.Username,
                Email = Input.Email,
                EmailConfirmed = true
            };

            var result = await _userManager.CreateAsync(user, Input.Password);
            if (!result.Succeeded) 
                return Page();

            _logger.LogInformation("User created a new account with password in admin page");
            return LocalRedirect(returnUrl);

        }
    }
}

src/EC_Website.Web/Pages/Admin/Users/Delete.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Core.Interfaces.Repositories;

namespace EC_Website.Web.Pages.Admin.Users
{
    [Authorize(Roles = "SuperAdmin")]
    public class DeleteModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUserRepository _userRepository;

        public DeleteModel(IUserRepository userRepository, UserManager<ApplicationUser> userManager)
        {
            _userRepository = userRepository;
            _userManager = userManager;
        }

        [BindProperty]
        public ApplicationUser AppUser { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            AppUser = await _userManager.Users.FirstOrDefaultAsync(i => i.Id == id);

            if (User == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            await _userRepository.DeleteDeeplyAsync(user);
            return RedirectToPage("./Index");
        }
    }
}

src/EC_Website.Web/Pages/Admin/Users/Edit.cshtml.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Core.Interfaces.Repositories;
using EC_Website.Infrastructure.Extensions;
using EC_Website.Web.Authorization;
using EC_Website.Web.Utils;

namespace EC_Website.Web.Pages.Admin.Users
{
    [Authorize(Policy = Policies.HasAdminRole)]
    public class EditModel : PageModel
    {
        private readonly IUserRepository _userRepository;
        private readonly RoleManager<UserRole> _roleManager;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ImageHelper _imageHelper;

        public EditModel(UserManager<ApplicationUser> userManager,
            RoleManager<UserRole> roleManager, ImageHelper imageHelper,
            IUserRepository userRepository)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _userRepository = userRepository;
            _imageHelper = imageHelper;
        }

        [BindProperty]
        public ApplicationUser AppUser { get; set; }

        [BindProperty]
        public IList<string> UserRolesName { get; set; }

        [BindProperty]
        public IList<string> UserBadgesName { get; set; }

        [BindProperty]
        public IFormFile ProfilePhoto { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            AppUser = await _userManager.FindByIdAsync(id);

            if (AppUser == null)
            {
                return NotFound();
            }

            var isUserRoleLower = await _userManager.CheckRoleLowerOrEqualAsync(User, AppUser);
            if (isUserRoleLower)
            {
                return LocalRedirect("/Identity/Account/AccessDenied");
            }

            List<UserRole> userRoles;
            if (User.IsInRole("SuperAdmin"))
            {
                // Only SuperAdmin can assign Admin or SuperAdmin roles
                userRoles = await _roleManager.Roles.ToListAsync();
            }
            else
            {
                // Exclude SuperAdmin and Admin roles
                userRoles = await _roleManager.Roles.Where(i => i.Role != Role.SuperAdmin && i.Role != Role.Admin).ToListAsync();
            }
            
            var userBadges = await _userRepository.GetListAsync<Badge>();
            ViewData.Add("userRoles", userRoles);
            ViewData.Add("userBadges", userBadges.Select(i => i.Name));

            UserRolesName = await _userManager.GetRolesAsync(AppUser);
            UserBadgesName = AppUser.UserBadges.Select(i => i.Badge.Name).ToList();

            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var user = await _userManager.FindByIdAsync(AppUser.Id);

            if (user == null)
            {
                return NotFound();
            }

            user.UserName = AppUser.UserName;
            user.Email = AppUser.Email;
            user.FirstName = AppUser.FirstName;
            user.LastName = AppUser.LastName;
            user.PhoneNumber = AppUser.PhoneNumber;
            user.Status = AppUser.Status;
            user.Bio = AppUser.Bio;
            user.IsBanned = AppUser.IsBanned;
            user.BanExpirationDate = AppUser.BanExpirationDate;
            await _userRepository.UpdateUserBadgesAsync(user, UserBadgesName);
            await _userRepository.UpdateUserRolesAsync(user, UserRolesName);

            if (ProfilePhoto != null)
            {
                user.ProfilePhotoPath = _imageHelper.UploadImage(ProfilePhoto, $"{user.Id}_profile", true);
            }

            await _userManager.UpdateAsync(user);
            return RedirectToPage("./Index");
        }
    }
}

src/EC_Website.Web/Pages/Forums/Board/Index.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using SuxrobGM.Sdk.AspNetCore.Pagination;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Core.Interfaces.Repositories;

namespace EC_Website.Web.Pages.Forums.Board
{
    public class IndexModel : PageModel
    {
        private readonly IForumRepository _forumRepository;
        private readonly UserManager<ApplicationUser> _userManager;

        public IndexModel(IForumRepository forumRepository, 
            UserManager<ApplicationUser> userManager)
        {
            _forumRepository = forumRepository;
            _userManager = userManager;
        }
        
        public ApplicationUser AppUser { get; set; }
        public Core.Entities.ForumModel.Board Board { get; set; }
        public PaginatedList<Core.Entities.ForumModel.Thread> PagedThreads { get; set; }

        public async Task<IActionResult> OnGetAsync(int pageIndex = 1)
        {
            var boardSlug = RouteData.Values["slug"].ToString();
            AppUser = await _userManager.GetUserAsync(User);
            Board = await _forumRepository.GetAsync<Core.Entities.ForumModel.Board>(i => i.Slug == boardSlug);
            
            if (Board == null)
            {
                return NotFound();
            }

            PagedThreads = PaginatedList<Core.Entities.ForumModel.Thread>.Create(Board.Threads, pageIndex, 25);
            return Page();
        }

        public async Task<IActionResult> OnPostAddToFavoriteThreadsAsync(string threadId)
        {
            var user = await _userManager.GetUserAsync(User);
            var thread = await _forumRepository.GetByIdAsync<Core.Entities.ForumModel.Thread>(threadId);

            if (thread == null)
            {
                return NotFound();
            }

            await _forumRepository.AddFavoriteThreadAsync(thread, user);
            return RedirectToPage();
        }

        public async Task<IActionResult> OnPostRemoveFromFavoriteThreadsAsync(string threadId)
        {
            var thread = await _forumRepository.GetByIdAsync<Core.Entities.ForumModel.Thread>(threadId);
            var user = await _userManager.GetUserAsync(User);
            await _forumRepository.RemoveFavoriteThreadAsync(thread, user);
            return RedirectToPage();
        }
    }
}

src/EC_Website.Web/ViewComponents/SearchBoxViewComponent.cs
using Microsoft.AspNetCore.Mvc;
using EC_Website.Web.ViewModels;

namespace EC_Website.Web.ViewComponents
{
    public class SearchBoxViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke()
        {
            var viewModel = new SearchViewModel();
            return View(viewModel);
        }
    }
}

src/EC_Website.Web/Pages/Forums/Board/Create.cshtml
@page
@model EC_Website.Web.Pages.Forums.Board.CreateModel
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["Create Board"];
}

<h1>@ViewData["Title"]</h1>

<h4>@Localizer["Board"]</h4>
<hr />
<div class="row">
    <div class="col-12 col-md-5">
        <form method="post" asp-route-forumId="@Model.Board.Forum.Id">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label class="control-label">@Localizer["Create board for forum"]: <span class="text-danger">@Model.Board.Forum.Title</span></label>
                <input class="form-control" asp-for="Board.Title" />
            </div>
            <div class="form-group">
                <label asp-for="Board.IsLocked" class="form-check-label"></label>
                <input asp-for="Board.IsLocked" class="form-check-inline" />
            </div>
            <div class="form-group">
                <input type="submit" value="@Localizer["Create"]" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="../Index">@Localizer["Back to List"]</a>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/EC_Website.Web/Pages/Forums/Board/Delete.cshtml
@page
@model EC_Website.Web.Pages.Forums.Board.DeleteModel
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["Delete Board"];
}

<h1>@ViewData["Title"]</h1>

<h3>@Localizer["Are you sure you want to delete this"]?</h3>
<div>
    <h4>@Localizer["Board"] "@Model.Board.Title"</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Board.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Board.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Board.Timestamp)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Board.Timestamp)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Board.Slug)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Board.Slug)
        </dd>
        <dt class="col-sm-2">
            @Localizer["Threads"]
        </dt>
        <dd class="col-sm-10">
            @Model.Board.Threads.Count
        </dd>
        <dt class="col-sm-2">
            @Localizer["Posts"]
        </dt>
        <dd class="col-sm-10">
            @Model.Board.Threads.SelectMany(i => i.Posts).Count()
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Board.Id" />
        <input type="submit" value="@Localizer["Delete"]" class="btn btn-danger" /> |
        <a asp-page="./Index" asp-route-slug="@Model.Board.Slug">@Localizer["Back to List"]</a>
    </form>
</div>

src/EC_Website.Web/Pages/Forums/Board/Edit.cshtml
@page
@model EC_Website.Web.Pages.Forums.Board.EditModel
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["Edit Board"];
}

<h1>@ViewData["Title"]</h1>

<h4>@Localizer["Board"] "@Model.Board.Title"</h4>
<hr />

<div class="row">
    <div class="col-12 col-md-5">
        <form method="post">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Board.Id" />
            <div class="form-group">
                <label class="control-label">@Localizer["Edit board for forum"]: <span class="text-danger">@Model.Board.Forum.Title</span></label>
                <input asp-for="Board.Title" class="form-control" />
                <span asp-validation-for="Board.Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Board.IsLocked" class="form-check-label"></label>
                <input asp-for="Board.IsLocked" class="form-check-inline" />
            </div>
            <div class="form-group">
                <input type="submit" value="@Localizer["Save"]" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-page="./Index" asp-route-slug="@Model.Board.Slug">@Localizer["Back to List"]</a>
</div>

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

src/EC_Website.Web/Pages/Forums/Board/Index.cshtml
@page "{slug}"
@model EC_Website.Web.Pages.Forums.Board.IndexModel
@inject IViewLocalizer Localizer
@inject IAuthorizationService Authorization

@{
    ViewData["Title"] = Model.Board.Title;
}

@section Head {
    @{
        var boardUrl = $"https://ec-hoi-mod.site/{Model.Board.Slug}";
    }

    <meta name="description" content="Board @Model.Board.Title - Economic Crisis Forum" />
    <meta name="keywords" content="global strategy, rts, game, hoi4, ec, economic crisis, economic crisis 2013, hoi 4, hoi4, hoi 4, hoi IV, hoi ec, hoi4 ec, mod, hearts of iron 4, hearts of iron IV, economic crisis forum" />
    <meta property="og:title" content="@Model.Board.Title" />
    <meta property="og:description" content="Board @Model.Board.Title - Economic Crisis Forum" />
    <meta property="og:site_name" content="Board @Model.Board.Title - Economic Crisis Forum" />
    <meta property="og:url" content="@boardUrl" />
    <meta name="twitter:title" content="@Model.Board.Title" />
    <meta name="twitter:description" content="Board @Model.Board.Title - Economic Crisis Forum" />
    <meta name="twitter:card" content="@Model.Board.Title" />
    <meta name="twitter:site" content="Board @Model.Board.Title - Economic Crisis Forum" />

    <link href="~/css/forum-theme.css" rel="stylesheet" />
}

<div class="forum">
    <div class="forum-header">
        <div class="row">
            <div class="col-9 col-md-10">
                <h1>@Model.Board.Title</h1>
            </div>
            <div class="col-3 col-md-2">
                @if ((await Authorization.AuthorizeAsync(User, Policies.CanManageForums)).Succeeded)
                {
                    <span class="float-right mt-2">
                        <a asp-page="../Thread/Create" asp-route-boardId="@Model.Board.Id" class="text-light" data-toggle="tooltip" data-placement="top" title="@Localizer["Add new thread"]"><i class="fas fa-plus-circle fa-lg"></i></a>
                        <a asp-page="./Edit" asp-route-id="@Model.Board.Id" class="text-light" data-toggle="tooltip" data-placement="top" title="@Localizer["Edit board"]"><i class="fas fa-wrench fa-lg"></i></a>
                        <a asp-page="./Delete" asp-route-id="@Model.Board.Id" class="text-light" data-toggle="tooltip" data-placement="top" title="@Localizer["Delete board"]"><i class="fas fa-times fa-lg"></i></a>
                    </span>
                }
            </div>
        </div>

        <ul class="breadcrumb text-primary mt-1 mb-0">
            <li class="breadcrumb-item"><a asp-page="../Index">@Model.Board.Forum.Title</a></li>
            <li class="breadcrumb-item"><a asp-page="../Board/Index" asp-route-slug="@Model.Board.Slug">@Model.Board.Title</a></li>
        </ul>
    </div>

    <div class="forum-body">
        <div class="forum-search-panel">
            <vc:search-box />
        </div>
        <div class="table-responsive">
            <table id="tableforum" class="table table-bordered">
                <thead class="forum-table-head">
                    <tr>
                        <th>
                            <strong>@Localizer["Thread"]</strong>
                        </th>
                        <th>
                            <strong>@Localizer["Author"]</strong>
                        </th>
                        <th>
                            <strong>@Localizer["Posts"]</strong>
                        </th>
                        <th>
                            <strong>@Localizer["Last Post"]</strong>
                        </th>
                        <th style="text-align: center">
                            <strong>+ @Localizer["Fav"]</strong>
                        </th>
                    </tr>
                    <tr class="forum-category">
                        <th colspan="3">
                            <strong>@Model.Board.Title</strong>
                        </th>
                        <th colspan="2" style="background-color: teal; text-align:center">
                            @if (User.Identity.IsAuthenticated && !Model.Board.IsLocked)
                            {
                                <a asp-page="../Thread/Create" asp-route-boardId="@Model.Board.Id" style="color: azure">@Localizer["New Thread"]</a>
                            }
                        </th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var thread in Model.PagedThreads.OrderByDescending(i => i.IsPinned))
                    {
                        <tr style="color: black">
                            <td>
                                @if (thread.IsLocked)
                                {
                                    <i class="fas fa-lock" data-toggle="tooltip" data-placement="top" title="@Localizer["This topic locked"]"></i>
                                }

                                @if (thread.IsPinned)
                                {
                                    <i class="fas fa-thumbtack" data-toggle="tooltip" data-placement="top" title="@Localizer["This topic pinned"]"></i>
                                }
                                <a asp-page="../Thread/Index" asp-route-slug="@thread.Slug" style="color: saddlebrown">@thread.Title</a>
                            </td>
                            <td>
                                <a asp-page="/User/Index" asp-route-username="@thread.Author.UserName">@thread.Author.UserName</a>
                            </td>
                            <td>
                                <label>@thread.Posts.Count</label>
                            </td>
                            <td>
                                @{
                                    if (thread.Posts.Count > 0)
                                    {
                                        var lastPost = thread.Posts.Last();
                                        <a asp-page="../Thread/Index" asp-route-slug="@thread.Slug" asp-fragment="@lastPost.Id">@lastPost.Author.UserName - @lastPost.Timestamp.ToShortDateString()</a>
                                    }
                                }
                            </td>
                            <td style="text-align: center">
                                @if (User.Identity.IsAuthenticated)
                                {
                                    if (Model.AppUser.FavoriteThreads.Any(i => i.ThreadId == thread.Id))
                                    {
                                        <form asp-page-handler="RemoveFromFavoriteThreads" asp-route-threadId="@thread.Id" method="post">
                                            <button class="btn btn-sm" data-toggle="tooltip" data-placement="top" title="@Localizer["Remove thread to favorites list"]"><i class="fa fa-minus-circle fa-lg text-danger"></i></button>
                                        </form>
                                    }
                                    else
                                    {
                                        <form asp-page-handler="AddToFavoriteThreads" asp-route-threadId="@thread.Id" method="post">
                                            <button class="btn btn-sm" data-toggle="tooltip" data-placement="top" title="@Localizer["Add thread to favorites list"]"><i class="fa fa-plus-circle fa-lg text-secondary"></i></button>
                                        </form>
                                    }
                                }
                            </td>
                        </tr>
                    }
                </tbody>
                <tfoot>
                    <tr>
                        <td colspan="5">
                            <div id="pagination" class="d-flex">
                                <pagination class="mx-auto" page-index="@Model.PagedThreads.PageIndex" total-pages="@Model.PagedThreads.TotalPages"
                                            page-path="/Forums/Board/@Model.Board.Slug" />
                            </div>
                        </td>
                    </tr>
                </tfoot>
            </table>
        </div>
    </div>
</div>