src/EC_Website.Web/Pages/Admin/UserBadges/Create.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Core.Interfaces.Repositories;
using EC_Website.Web.Authorization;

namespace EC_Website.Web.Pages.Admin.UserBadges
{
    [Authorize(Policy = Policies.HasAdminRole)]
    public class CreateModel : PageModel
    {
        private readonly IRepository _repository;

        public CreateModel(IRepository repository)
        {
            _repository = repository;
        }

        public IActionResult OnGet()
        {
            return Page();
        }

        [BindProperty]
        public Badge Badge { get; set; }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            await _repository.AddAsync(Badge);
            return RedirectToPage("./Index");
        }
    }
}

src/EC_Website.Web/Pages/Admin/UserBadges/Delete.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Core.Interfaces.Repositories;
using EC_Website.Web.Authorization;

namespace EC_Website.Web.Pages.Admin.UserBadges
{
    [Authorize(Policy = Policies.HasAdminRole)]
    public class DeleteModel : PageModel
    {
        private readonly IRepository _repository;

        public DeleteModel(IRepository repository)
        {
            _repository = repository;
        }

        [BindProperty]
        public Badge Badge { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Badge = await _repository.GetByIdAsync<Badge>(id);

            if (Badge == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            await _repository.DeleteAsync(Badge);
            return RedirectToPage("./Index");
        }
    }
}

src/EC_Website.Web/Pages/Admin/UserBadges/Edit.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Core.Interfaces.Repositories;
using EC_Website.Web.Authorization;

namespace EC_Website.Web.Pages.Admin.UserBadges
{
    [Authorize(Policy = Policies.HasAdminRole)]
    public class EditModel : PageModel
    {
        private readonly IRepository _repository;

        public EditModel(IRepository repository)
        {
            _repository = repository;
        }

        [BindProperty]
        public Badge Badge { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Badge = await _repository.GetByIdAsync<Badge>(id);

            if (Badge == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var badge = await _repository.GetByIdAsync<Badge>(Badge.Id);

            if (badge == null)
            {
                return NotFound();
            }

            badge.Name = Badge.Name;
            badge.Description = Badge.Description;
            await _repository.UpdateAsync(badge);
            return RedirectToPage("./Index");
        }
    }
}

src/EC_Website.Web/Pages/Admin/UserRoles/Edit.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Web.Authorization;

namespace EC_Website.Web.Pages.Admin.UserRoles
{
    [Authorize(Policy = Policies.HasAdminRole)]
    public class EditModel : PageModel
    {
        private readonly RoleManager<UserRole> _roleManager;

        public EditModel(RoleManager<UserRole> roleManager)
        {
            _roleManager = roleManager;
        }

        [BindProperty]
        public UserRole UserRole { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            UserRole = await _roleManager.FindByIdAsync(id);

            if (UserRole == null)
            {
                return NotFound();
            }
            return Page();
        }

        // To protect from overposting attacks, enable the specific properties you want to bind to, for
        // more details, see https://aka.ms/RazorPagesCRUD.
        public async Task<IActionResult> OnPostAsync()
        {
            if (!ModelState.IsValid)
            {
                return Page();
            }

            var userRole = await _roleManager.FindByIdAsync(UserRole.Id);

            if (userRole == null)
            {
                return NotFound();
            }
            
            userRole.Description = UserRole.Description;
            await _roleManager.UpdateAsync(userRole);
            return RedirectToPage("./Index");
        }
    }
}

src/EC_Website.Web/Pages/Admin/Users/Create.cshtml.cs
using System.ComponentModel.DataAnnotations;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Web.Authorization;

namespace EC_Website.Web.Pages.Admin.Users
{
    [Authorize(Policy = Policies.HasAdminRole)]
    public class CreateModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly ILogger<CreateModel> _logger;

        public CreateModel(UserManager<ApplicationUser> userManager,
            ILogger<CreateModel> logger)
        {
            _userManager = userManager;
            _logger = logger;
        }

        [BindProperty]
        public InputModel Input { get; set; }

        public string ReturnUrl { get; set; }

        public class InputModel
        {
            [Required]
            [DataType(DataType.Text)]
            [Display(Name = "Username")]
            public string Username { get; set; }

            [Required]
            [EmailAddress]
            [Display(Name = "Email")]
            public string Email { get; set; }

            [Required]
            [StringLength(100, ErrorMessage = "The {0} must be at least {2} and at max {1} characters long.", MinimumLength = 6)]
            [DataType(DataType.Password)]
            [Display(Name = "Password")]
            public string Password { get; set; }

            [DataType(DataType.Password)]
            [Display(Name = "Confirm Password")]
            [Compare("Password", ErrorMessage = "The password and confirmation password do not match.")]
            public string ConfirmPassword { get; set; }
        }

        public void OnGet(string returnUrl = null)
        {
            ReturnUrl = returnUrl;
        }

        public async Task<IActionResult> OnPostAsync(string returnUrl = null)
        {
            returnUrl ??= Url.Content("~/");

            if (!ModelState.IsValid) 
                return Page();

            var user = new ApplicationUser
            {
                UserName = Input.Username,
                Email = Input.Email,
                EmailConfirmed = true
            };

            var result = await _userManager.CreateAsync(user, Input.Password);
            if (!result.Succeeded) 
                return Page();

            _logger.LogInformation("User created a new account with password in admin page");
            return LocalRedirect(returnUrl);

        }
    }
}

src/EC_Website.Web/Pages/Admin/Users/Delete.cshtml.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Core.Interfaces.Repositories;

namespace EC_Website.Web.Pages.Admin.Users
{
    [Authorize(Roles = "SuperAdmin")]
    public class DeleteModel : PageModel
    {
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly IUserRepository _userRepository;

        public DeleteModel(IUserRepository userRepository, UserManager<ApplicationUser> userManager)
        {
            _userRepository = userRepository;
            _userManager = userManager;
        }

        [BindProperty]
        public ApplicationUser AppUser { get; set; }

        public async Task<IActionResult> OnGetAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            AppUser = await _userManager.Users.FirstOrDefaultAsync(i => i.Id == id);

            if (User == null)
            {
                return NotFound();
            }
            return Page();
        }

        public async Task<IActionResult> OnPostAsync(string id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var user = await _userManager.FindByIdAsync(id);
            await _userRepository.DeleteDeeplyAsync(user);
            return RedirectToPage("./Index");
        }
    }
}

src/EC_Website.Web/Pages/Blog/Ajax.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Core.Interfaces.Repositories;

namespace EC_Website.Web.Pages.Blog
{
    public class AjaxModel : PageModel
    {
        private readonly IBlogRepository _blogRepository;
        private readonly UserManager<ApplicationUser> _userManager;

        public AjaxModel(IBlogRepository blogRepository,
            UserManager<ApplicationUser> userManager)
        {
            _blogRepository = blogRepository;
            _userManager = userManager;
        }

        public void OnGet()
        {

        }

        public async Task<IActionResult> OnGetLikeArticleAsync(string blogId)
        {
            var blog = await _blogRepository.GetByIdAsync<Core.Entities.BlogModel.Blog>(blogId);
            var user = await _userManager.GetUserAsync(User);
            
            if (string.IsNullOrEmpty(blogId) || blog == null)
            {
                return BadRequest($"Specified blog with {blogId} could not be found");
            }

            var alreadyLiked = blog.LikedUsers.Any(i => i.UserId == user.Id);

            if (alreadyLiked)
            {
                await _blogRepository.RemoveLikeAsync(blog, user);
            }
            else
            {
                await _blogRepository.AddLikeAsync(blog, user);
            }

            return new OkObjectResult(blog.LikedUsers.Count);
        }
    }
}

src/EC_Website.Web/Pages/Blog/Index.cshtml.cs
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.AspNetCore.Identity;
using SuxrobGM.Sdk.AspNetCore.Pagination;
using EC_Website.Core.Entities.BlogModel;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Core.Interfaces.Repositories;
using EC_Website.Core.Interfaces.Services;

namespace EC_Website.Web.Pages.Blog
{
    public class IndexModel : PageModel
    {
        private readonly IBlogRepository _blogRepository;
        private readonly IEmailSender _emailSender;
        private readonly UserManager<ApplicationUser> _userManager;

        public IndexModel(IBlogRepository blogRepository,
            IEmailSender emailSender,
            UserManager<ApplicationUser> userManager)
        {
            _blogRepository = blogRepository;
            _emailSender = emailSender;
            _userManager = userManager;
        }
       
        public Core.Entities.BlogModel.Blog Blog { get; set; }
        public PaginatedList<Comment> Comments { get; set; }

        [BindProperty]
        public string CommentContent { get; set; }
        public string Tags { get; set; }

        public async Task<IActionResult> OnGetAsync(int pageIndex = 1, bool increaseViewCount = true)
        {
            var blogSlug = RouteData.Values["slug"].ToString();
            ViewData["PageIndex"] = pageIndex;
            Blog = await _blogRepository.GetAsync<Core.Entities.BlogModel.Blog>(i => i.Slug == blogSlug);

            if (Blog == null)
            {
                return NotFound();
            }

            Comments = PaginatedList<Comment>.Create(Blog.Comments, pageIndex);
            Tags = Tag.JoinTags(Blog.BlogTags.Select(i => i.Tag));

            if (increaseViewCount && !Request.Headers["User-Agent"].ToString().ToLower().Contains("bot"))
            {
                Blog.ViewCount++;
            }

            await _blogRepository.UpdateAsync(Blog);
            return Page();
        }
        
        public async Task<IActionResult> OnPostAddCommentAsync()
        {
            var blogSlug = RouteData.Values["slug"].ToString();

            if (!int.TryParse(HttpContext.Request.Query["pageIndex"].ToString(), out var pageNumber))
            {
                pageNumber = 1;
            }

            if (string.IsNullOrWhiteSpace(CommentContent))
            {
                ModelState.AddModelError("CommentContent", "Empty comment content");
                return Page();
            }

            var blog = await _blogRepository.GetAsync<Core.Entities.BlogModel.Blog>(i => i.Slug == blogSlug);
            var author = await _userManager.GetUserAsync(User);
            var comment = new Comment()
            {
                Author = author,
                Content = CommentContent
            };

            await _blogRepository.AddCommentAsync(blog, comment);
            return RedirectToPage("", "", new { pageIndex = pageNumber }, comment.Id);
        }

        public async Task<IActionResult> OnPostReplyToCommentAsync(string commentId)
        {
            if (!int.TryParse(HttpContext.Request.Query["pageIndex"].ToString(), out var pageNumber))
            {
                pageNumber = 1;
            }

            if (string.IsNullOrWhiteSpace(CommentContent))
            {
                ModelState.AddModelError("CommentContent", "Empty comment content");
                return Page();
            }
            
            var comment = await _blogRepository.GetByIdAsync<Comment>(commentId);
            var author = await _userManager.GetUserAsync(User);
            var commentReply = new Comment()
            {
                Author = author,
                Blog = comment.Blog,
                Content = CommentContent
            };

            // TODO
            // Need to implement emailSender to notify parent comment author about comment reply

            await _blogRepository.AddReplyToCommentAsync(comment, commentReply);
            return RedirectToPage("", "", new { pageIndex = pageNumber } ,commentId);
        }

        public async Task<IActionResult> OnPostDeleteCommentAsync(string commentId)
        {
            if (!int.TryParse(HttpContext.Request.Query["pageIndex"].ToString(), out var pageNumber))
            {
                pageNumber = 1;
            }
            var comment = await _blogRepository.GetByIdAsync<Comment>(commentId);
            await _blogRepository.DeleteCommentAsync(comment);
            return RedirectToPage("", "", new { pageIndex = pageNumber });
        }
    }
}

src/EC_Website.Web/ViewComponents/AlertBoxViewComponent.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using EC_Website.Core.Entities.UserModel;
using EC_Website.Web.ViewModels;

namespace EC_Website.Web.ViewComponents
{
    public class AlertBoxViewComponent : ViewComponent
    {
        public IViewComponentResult Invoke(string message, AlertType alertType = AlertType.Success, bool dismissible = true)
        {
            var alertBox = new AlertBoxViewModel(message)
            {
                AlertType = alertType,
                IsDismissible = dismissible
            };
            return View(alertBox);
        }
    }
}

src/EC_Website.Web/Pages/Blog/Ajax.cshtml
@page
@model EC_Website.Web.Pages.Blog.AjaxModel
@{
    ViewData["Title"] = "Ajax";
}

<h1>Ajax</h1>

src/EC_Website.Web/Pages/Blog/Delete.cshtml
@page
@model EC_Website.Web.Pages.Blog.DeleteModel
@inject IViewLocalizer Localizer

@{
    ViewData["Title"] = Localizer["Delete Blog"];
}

<h1>@ViewData["Title"]</h1>

<h3>@Localizer["Are you sure you want to delete this"]?</h3>
<div>
    <h4>@Localizer["Article"]</h4>
    <hr />
    <dl class="row">
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Blog.Title)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Blog.Title)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Blog.Summary)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Blog.Summary)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Blog.Content)
        </dt>
        <dd class="col-sm-10">
            @Html.Raw(Model.Blog.Content)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Blog.Slug)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Blog.Slug)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Tags)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Tags)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Blog.Timestamp)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Blog.Timestamp)
        </dd>
        <dt class="col-sm-2">
            @Html.DisplayNameFor(model => model.Blog.Author)
        </dt>
        <dd class="col-sm-10">
            @Html.DisplayFor(model => model.Blog.Author.UserName)
        </dd>
    </dl>
    
    <form method="post">
        <input type="hidden" asp-for="Blog.Id" />
        <input type="submit" value="@Localizer["Delete"]" class="btn btn-danger" /> |
        <a asp-page="./Index" asp-route-slug="@Model.Blog.Slug">@Localizer["Back to Article"]</a>
    </form>
</div>

src/EC_Website.Web/Pages/Blog/Index.cshtml
@page "{slug}"
@inject IViewLocalizer Localizer
@inject IAuthorizationService Authorization
@inject UserManager<ApplicationUser> UserManager
@model EC_Website.Web.Pages.Blog.IndexModel

@{
    ViewData["Title"] = Model.Blog.Title;
}

@section Head {
    @{
        var imgUrl = $"https://ec-hoi-mod.site{Model.Blog.CoverPhotoPath}";
        var articleUrl = $"https://ec-hoi-mod.site/blog/{Model.Blog.Slug}";
    }

    <meta name="author" content="@Model.Blog.Author.UserName" />
    <meta name="description" content="@Model.Blog.Summary" />
    <meta name="keywords" content="@Model.Tags, global strategy, rts, game, hoi4, ec, economic crisis, economic crisis 2013, hoi 4, hoi4, hoi 4, hoi IV, hoi ec, hoi4 ec, mod, hearts of iron 4, hearts of iron IV, economic crisis forum" />
    <meta name="image" content="@imgUrl" />
    <meta property="og:title" content="@Model.Blog.Title" />
    <meta property="og:description" content="@Model.Blog.Summary" />
    <meta property="og:site_name" content="Hearts of Iron IV: Economic Crisis Dev Blog" />
    <meta property="og:type" content="article" />
    <meta property="og:image" content="@imgUrl" />
    <meta property="og:url" content="@articleUrl" />
    <meta property="article:published_time" content="@Model.Blog.Timestamp" />
    <meta property="article:author" content="@Model.Blog.Author.UserName" />
    <meta property="article:tags" content="@Model.Tags" />
    <meta name="twitter:title" content="@Model.Blog.Title" />
    <meta name="twitter:description" content="@Model.Blog.Summary" />
    <meta name="twitter:creator" content="@Model.Blog.Author.UserName" />
    <meta name="twitter:card" content="@Model.Blog.Summary" />
    <meta name="twitter:site" content="Hearts of Iron IV: Economic Crisis Dev Blog" />
    <meta name="twitter:image" content="@imgUrl" />
}

<div class="card shadow-sm mb-4">
    <div class="card-header">
        <b>@Model.Blog.Title</b>
        <div class="float-right">
            <span class="font-italic">@Model.Blog.Timestamp.ToString("MMMM dd, yyyy")</span>
            <span class="mx-2"><i class="fa fa-eye"></i>&nbsp;@Model.Blog.ViewCount</span>
            @{
                var likesCount = Model.Blog.LikedUsers.Count;
                if (!User.Identity.IsAuthenticated)
                {
                    <a class="mx-2 text-dark text-decoration-none" asp-area="Identity" asp-page="/Account/Login" data-toggle="tooltip" data-placement="top" title="@Localizer["Sign in to like this article"]">
                        <i class="far fa-heart">&nbsp;@likesCount</i>
                    </a>
                }
                else
                {
                    <button class="btn btn-sm" data-toggle="tooltip" data-placement="top" title="@Localizer["Like this article"]" onclick="likeArticle('@Model.Blog.Id')">
                        @if (Model.Blog.LikedUsers.Any(i => i.User.UserName == User.Identity.Name))
                        {
                            <i id="@Model.Blog.Id-likes-count" class="fas fa-heart">&nbsp;@likesCount</i>
                        }
                        else
                        {
                            <i id="@Model.Blog.Id-likes-count" class="far fa-heart">&nbsp;@likesCount</i>
                        }
                    </button>
                }
            }

            @if ((await Authorization.AuthorizeAsync(User, Policies.CanManageBlogs)).Succeeded)
            {
                <a class="mx-2" asp-page="./Edit" asp-route-id="@Model.Blog.Id" data-toggle="tooltip" data-placement="top" title="@Localizer["Edit this article"]" style="color: black"><i class="fa fa-wrench"></i></a>
                <a class="mx-2" asp-page="./Delete" asp-route-Id="@Model.Blog.Id" data-toggle="tooltip" data-placement="top" title="@Localizer["Delete this article"]" style="color: black"><i class="fa fa-times"></i></a>
            }
        </div>
    </div>
    <div class="card-body mb-2 p-2 p-sm-3 p-lg-4">
        @Html.Raw(Model.Blog.Content)
    </div>
    <div class="card-footer">
        <b>@Localizer["Tags"]</b><br />
        @foreach (var blogTag in Model.Blog.BlogTags)
        {
            <span class="badge badge-dark mr-2">@blogTag.Tag.Name</span>
        }
    </div>
</div>

@if (Model.Blog.Comments.Count > 0)
{
    <div id="comments" class="mb-2">
        @foreach (var comment in Model.Comments)
        {
            if (comment.Parent == null)
            {
                <partial name="_CommentsPartial" for="@comment" view-data="ViewData" />
            }
        }

        <div id="pagination" class="d-flex">
            <pagination class="mx-auto" page-index="@Model.Comments.PageIndex" total-pages="@Model.Comments.TotalPages"
                        page-fragment="pagination" page-path="@Model.Blog.Slug" />
        </div>
    </div>
}


@if (User.Identity.IsAuthenticated)
{
    var user = await UserManager.GetUserAsync(User);
    if (user.IsBanned)
    {
        <vc:alert-box alert-type="@AlertType.Error" dismissible="true"
                      message="You banned, and you can not write comments until @user.BanExpirationDate?.ToShortDateString()" />
    }
    else
    {
        <div id="comment_textbox" class="card card-header shadow-sm my-4 p-2">
            <label><b>@Localizer["Post comment"]</b></label>
            <span asp-validation-for="@Model.CommentContent" class="text-danger"></span>
            <form method="post" asp-page-handler="AddComment">
                <div class="bg-white">
                    <textarea asp-for="@Model.CommentContent" class="comment-editor emojis" rows="4" placeholder="@Localizer["Type message..."]" required>
                    </textarea>
                </div>
                <input type="submit" class="btn btn-sm btn-info shadow-sm mt-2" value="@Localizer["Save comment"]" />
            </form>
            
        </div>
    }
}

src/EC_Website.Web/Pages/Blog/_CommentsPartial.cshtml
@model EC_Website.Core.Entities.BlogModel.Comment
@inject IAuthorizationService Authorization
@inject IViewLocalizer Localizer
@inject RealTimeDataContext RealTimeContext

<div id="@Model.Id" class="d-flex my-2">
    <div class="img-container">
        @{
            var userOnline = RealTimeContext.OnlineUsers.Contains(Model.Author.UserName);
            var statusColor = userOnline ? "bg-success" : "bg-secondary";
        }
        <div class="status-icon-article @statusColor"></div>
        <img class="rounded-circle mr-2" src="@Model.Author.ProfilePhotoPath" alt="@Model.Author.UserName" style="width: 50px; height: 50px" onclick="window.location = '/User/@Model.Author.UserName'" />
    </div>
    <div class="card shadow-sm flex-grow-1">
        <div class="card-body p-2">
            <div class="mb-4">
                <a id="comment_author" class="text-primary mr-3" asp-page="/User/Index" asp-route-username="@Model.Author.UserName" style="font-size: smaller">
                    @Model.Author.UserName
                </a>
                <span class="text-muted font-weight-light" style="font-size: small">
                    @Model.Timestamp
                </span>
                <div class="float-right">
                    @if (Model.Replies.Any())
                    {
                        var targetElement = $"#{Model.Id}.card-footer";
                        <button class="btn btn-sm" onclick="collapseElement('@targetElement')"><i class="fa fa-angle-down fa-lg"></i></button>
                    }
                    
                    @if ((await Authorization.AuthorizeAsync(User, Policies.CanBanUsers)).Succeeded)
                    {
                        <a asp-page="/Admin/Users/Restrict" asp-route-id="@Model.Author.Id" asp-route-returnUrl="/Blog/Index/@Model.Blog.Slug" 
                           class="text-dark" data-toggle="tooltip" data-placement="top" title="@Localizer["Edit user ban"]">
                            <i class="fas fa-ban"></i>
                        </a>
                    }

                    @if (User.Identity.Name == Model.Author.UserName || 
                         (await Authorization.AuthorizeAsync(User, Policies.CanManageBlogs)).Succeeded)
                    {
                        <form asp-page-handler="DeleteComment" asp-route-commentId="@Model.Id" asp-route-pageIndex="@ViewData["PageIndex"]" class="float-right" method="post">
                            <button class="btn btn-sm delete-item" data-toggle="tooltip" data-placement="top" title="@Localizer["Delete comment"]"><i class="fa fa-times"></i></button>
                        </form>
                    }

                    @if (User.Identity.IsAuthenticated)
                    {
                        <button id="@Model.Id" class="btn btn-sm float-right" data-toggle="tooltip" data-placement="top" title="@Localizer["Reply to this comment"]" onclick="showReplyCommentBox('@Model.Id')"><i class="fa fa-reply"></i></button>
                    }
                </div>
            </div>
            <div>
                @Html.Raw(Model.Content)
            </div>
        </div>
        <div id="@Model.Id" class="card-footer collapse p-0 p-sm-2">
            @foreach (var reply in Model.Replies)
            {
                <partial name="_CommentsPartial" model="reply" />
            }

            <div id="@Model.Id" class="reply-commentbox ml-1 d-none">
                <form asp-page-handler="ReplyToComment" asp-route-commentId="@Model.Id" asp-route-pageIndex="@ViewData["PageIndex"]" class="w-100" method="post">
                    <div class="bg-white border border-dark p-2">
                        <span data-valmsg-for="CommentContent" data-valmsg-replace="true" class="text-danger"></span>
                        <textarea id="CommentText" name="CommentContent" class="comment-editor emojis" rows="4" placeholder="@Localizer["Type message..."]" required></textarea>
                    </div>
                    <div class="mt-2">
                        <input type="submit" class="btn btn-sm btn-info shadow-sm" value="@Localizer["Reply"]" onclick="hideReplyCommentBox('@Model.Id')" />
                        <input type="button" class="btn btn-sm border shadow-sm" value="@Localizer["Cancel"]" onclick="hideReplyCommentBox('@Model.Id')" />
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>